language: node_js
sudo: required
python:
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get install python-dev python3-pip graphicsmagick
  - python -m pip install --upgrade pip
  - python -m pip install pytest
  - pip install -r requirements.txt
  - python -m pip install .
  - yarn global add typescript
  - yarn install
  - yarn build
script:
  - pytest
  - yarn e2e
  - yarn test
